"""Aerodrome favorites — anonymous, device-id keyed bookmarks.

Phase 1: no login. The client generates a UUID v4 once, stores it in
`localStorage` and sends it as `X-Device-Id` on every request. The server
treats the header as opaque ownership and never tries to associate device
ids across requests.

Returned payload is intentionally minimal (icao + created_at). The frontend
hydrates the cards via the existing aerodrome endpoints — keeps the gateway
out of cross-schema joins and lets React Query parallelise the fetches.
"""

from __future__ import annotations

from fastapi import APIRouter, Depends, Header, HTTPException, Response, status
from sqlalchemy import select
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.orm import Session

from app.db import get_db
from app.models.favorite import Favorite
from app.schemas.favorite import FavoriteCreate, FavoriteOut

router = APIRouter(prefix="/api/favorites", tags=["favorites"])

_DEVICE_ID_MIN = 8
_DEVICE_ID_MAX = 64


def require_device_id(
    x_device_id: str | None = Header(
        default=None,
        alias="X-Device-Id",
        description=(
            "Opaque per-device identifier (UUID v4 generated by the client). "
            "Required on every favorites request."
        ),
    ),
) -> str:
    if not x_device_id:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="X-Device-Id header is required.",
        )
    value = x_device_id.strip()
    if not (_DEVICE_ID_MIN <= len(value) <= _DEVICE_ID_MAX):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"X-Device-Id must be {_DEVICE_ID_MIN}-{_DEVICE_ID_MAX} characters.",
        )
    return value


@router.get(
    "",
    response_model=list[FavoriteOut],
    summary="List favorites for the current device",
    description=(
        "Returns all aerodromes the calling device has marked as favorite, "
        "sorted alphabetically by ICAO. Enrichment (card data) is left to "
        "the client — use the `/api/aerodromes` endpoints to fetch details."
    ),
)
def list_favorites(
    device_id: str = Depends(require_device_id),
    db: Session = Depends(get_db),
) -> list[FavoriteOut]:
    rows = db.execute(
        select(Favorite)
        .where(Favorite.device_id == device_id)
        .order_by(Favorite.icao.asc())
    ).scalars().all()
    return [FavoriteOut.model_validate(row) for row in rows]


@router.post(
    "",
    response_model=FavoriteOut,
    status_code=status.HTTP_201_CREATED,
    summary="Mark an aerodrome as favorite (idempotent)",
    description=(
        "Adds an aerodrome to the calling device's favorites. Idempotent: "
        "re-posting the same ICAO returns the existing entry unchanged."
    ),
)
def add_favorite(
    payload: FavoriteCreate,
    device_id: str = Depends(require_device_id),
    db: Session = Depends(get_db),
) -> FavoriteOut:
    stmt = (
        pg_insert(Favorite)
        .values(device_id=device_id, icao=payload.icao)
        .on_conflict_do_nothing(index_elements=["device_id", "icao"])
    )
    db.execute(stmt)
    db.commit()

    row = db.execute(
        select(Favorite).where(
            Favorite.device_id == device_id,
            Favorite.icao == payload.icao,
        )
    ).scalar_one()
    return FavoriteOut.model_validate(row)


@router.delete(
    "/{icao}",
    status_code=status.HTTP_204_NO_CONTENT,
    response_class=Response,
    summary="Remove an aerodrome from favorites (idempotent)",
    description=(
        "Removes the given ICAO from the calling device's favorites. "
        "Always returns 204 — removing a non-existing favorite is a no-op."
    ),
)
def remove_favorite(
    icao: str,
    device_id: str = Depends(require_device_id),
    db: Session = Depends(get_db),
):
    normalized = icao.strip().upper()
    favorite = db.get(Favorite, (device_id, normalized))
    if favorite is not None:
        db.delete(favorite)
        db.commit()
    return Response(status_code=status.HTTP_204_NO_CONTENT)
